---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: label-controller
  labels:
    pramodbindal.dev/release: "devel"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-controller
  template:
    metadata:
      labels:
        app: label-controller
        pramodbindal.dev/release: "devel"
    spec:
      serviceAccountName: pramodbindal
      containers:
        - name: controller
          image: ko://github.com/pramodbindal/auto-labeler/cmd/controller
          env:
            - name: CONFIG_LOGGING_NAME
              value: config-logging-labeler
            - name: ENABLE_LEADER_ELECTION
              value: "false"
            - name: KUBERNETES_MIN_VERSION
              value: "1.20.0"
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
#  serviceName: label-controller
